title: "Not just surviving, thriving!"
date: 2020-10-23
author: Priscilla Aubrey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Healing from toxic relationships in a healthy manner

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
